config/routes.rb
Marketplace::Application.routes.draw do
  root :to => 'offers#index'
  resources :offers
  match "/signout" => "sessions#destroy", :as => :signout
  match "/faq" => "sessions#faq", :as => :faq
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  get "user" => 'users#edit', :as => :edit_user
  put "user" => 'users#update', :as => :update_user

end

app/models/offer.rb
class Offer < ActiveRecord::Base
  belongs_to :user
  belongs_to :plane
  belongs_to :part
  attr_accessible :active, :comment, :plane_id, :part_id, :user_id

  validates :user, :presence => {:message => 'You must be logged in to create an offer'}
  validates :plane, :presence => {:message => 'You must select a plane'}
  validates :comment, :presence => {:message => 'You must enter a comment'}

  self.per_page = 10
  
  scope :active, -> { where(:active => true) }
end

app/models/part.rb
class Part < ActiveRecord::Base
  attr_accessible :name
  default_scope order('name ASC')
end

app/models/plane.rb
class Plane < ActiveRecord::Base
  attr_accessible :name, :unlock_level
  default_scope order('unlock_level ASC')
  
  validates_presence_of :name
  validates_presence_of :unlock_level
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :omniauthable, :omniauth_providers => [:google_oauth2]

  after_create  :send_welcome_email
  validates_presence_of :gamecenter_id, :on => :update
  attr_accessible :email, :encrypted_password, :name, :gamecenter_id

  def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
      data = access_token.info
      user = User.where(:email => data["email"]).first
      unless user
        user = User.create(:name => data["name"],
          :email => data["email"],
          :encrypted_password => Devise.friendly_token[0,20]
        )
      end
      user
  end
  
  private
  def send_welcome_email
    logger.info "Sending welcome email to #{self.email}"
    UserMailer.welcome_email(self).deliver
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_filter :find_offer, :only => [:show, :edit, :update, :destroy]

  def index
    @offers = Offer.active.includes(:plane, :part, :user).paginate(:page => params[:page])
  end

  def new
    @offer = Offer.new
  end

  def edit
    redirect_to offers_path, :notice => "You cannot edit that offer" unless session[:user_id] == @offer.user_id
  end

  def create
    @offer = Offer.new(params[:offer].merge(:active => true, :user_id => session[:user_id]))

    if @offer.save
      redirect_to @offer, :notice => 'Offer was successfully created.'
    else
      render :action => "new"
    end
  end

  def update
    if @offer.update_attributes(params[:offer])
      redirect_to @offer, :notice => 'Offer was successfully updated.'
    else
      render :action => "edit"
    end
  end

  def destroy
    if session[:user_id] == @offer.user_id
      @offer.destroy 
      notice = "Offer successfully destroyed"
    else
      notice = "You cannot delete an offer that doesn't belong to you"
    end
    redirect_to offers_url, :notice => notice
  end

  private
  def find_offer
    if @offer = Offer.active.find_by_id(params[:id])
      true
    else
      redirect_to offers_path, :notice => "Offer not found"
      false
    end
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    user = User.find_for_google_oauth2(request.env["omniauth.auth"])
    if user.persisted?
      sign_in(:user, user)
      session[:user_id] = user.id

      if user.gamecenter_id.nil?
        redirect_to edit_user_path, :notice => "Please update your user profile with a Apple gamecenter id"
      else
        redirect_to root_path, :notice => "Successfully authenticated #{user.email}"
      end
    else
      redirect_to root_path, :notice => "Login failed"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def destroy
    reset_session
    redirect_to root_url, :notice => "Signed out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :find_user

  def update
    if @user.update_attributes(params[:user])
      redirect_to root_path, :notice => 'User was successfully updated'
    else
      render :action => "edit"
    end
  end

  private
  def find_user
    if @user = User.find_by_id(session[:user_id])
      true
    else
      redirect_to offers_path, :notice => "You must log in first" 
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/offers_helper.rb
module OffersHelper
  def offer_type(offer)
    if offer.new_record?
      "New"
    else
      "Edit"
    end
  end
  
  def editable?(offer)
    session[:user_id] == offer.user_id
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bids/_form.html.erb
<%= form_for(@bid) do |f| %>
  <% if @bid.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bid.errors.count, "error") %> prohibited this bid from being saved:</h2>

      <ul>
      <% @bid.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="small-3 columns">
      <%= f.label :comment, class: "right inline", title: "Additional information", data: {tooltip: true } %>
    </div>
    <div class="small-9 columns">
      <%= f.text_field :comment %>
    </div>
  </div>
  <div class="row">
    <div class="small-3 columns">
      <%= f.label :active, class: "right inline" %>
    </div>
    <div class="small-9 columns">
      <%= f.check_box :active %>
    </div>
  </div>
  <div class="row">
    <div class="small-9 small-offset-3 columns">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title>Pocket Planes Marketplace</title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="row">
      <div class="large-12 columns">

        <!-- Navigation -->
        <div class="row">
          <div class="large-12 columns">
            <nav class="top-bar">
              <ul class="title-area">
                <li class="name">
                  <h1><%= link_to "Pocket Planes Marketplace", offers_path %></a></h1>
                </li>
              </ul>
              <section class="top-bar-section">
                <ul class="right">
                  <% if user_signed_in? %>
                  <li class="divider"></li>
                  <li><%= link_to "Create Offer", new_offer_path %></li>
                  <li class="divider"></li>
                  <li><%= link_to "Profile", edit_user_path %></li>
                  <li class="divider"></li>
                  <li><%= link_to "Logout", signout_path %></li>
                  <li class="divider"></li>
                  <% else %>
                  <li><%= link_to "Sign in with Google", user_omniauth_authorize_path(:google_oauth2) %></li>
                  <li class="divider"></li>
                  <% end %>
                  <li><%= link_to('FAQ', faq_path) %></li>
                </ul>
              </div>
            </section>
          </nav>
        </div>
      </div>

      <div class="row">

        <!-- Side Bar -->
        <div class="large-4 small-12 columns">
          <img src="http://placehold.it/500x500&text=Logo">
          <div class="hide-for-small panel">
            <h3>Header</h3>
            <h5 class="subheader">Risus ligula, aliquam nec fermentum vitae, sollicitudin eget urna. Donec dignissim nibh fermentum odio ornare sagittis.
            </h5>
          </div>
          <a href="#">
          <div class="panel callout radius">
            <h6>99&nbsp; items in your cart</h6>
          </div>
          </a>
        </div>

        <!-- End Side Bar -->
        
        <!-- Thumbnails -->

        <div class="large-8 columns">
          <div class="row">
            <%= yield %>
          </div>

          <!-- End Thumbnails -->

          <!-- Managed By -->
          <div class="row">
            <div class="large-12 columns">
              <div class="panel">
                <div class="row">

                  <div class="large-2 small-6 columns">
                    <img src="http://placehold.it/300x300&text=Site Owner">
                  </div>

                  <div class="large-10 small-6 columns">
                    <strong>This Site Is Managed By<hr/></strong>

                    Risus ligula, aliquam nec fermentum vitae, sollicitudin eget urna. Donec dignissim nibh fermentum odio ornare sagittis
                  </div>

                </div>
              </div>
            </div>

            <!-- End Managed By -->

          </div>
        </div>
      </div>

      <!-- Footer -->

      <footer class="row">
        <div class="large-12 columns"><hr />
          <div class="row">

            <div class="large-6 columns">
              <p>&copy; Copyright no one at all. Go to town.</p>
            </div>

            <div class="large-6 columns">
              <ul class="inline-list right">
                <li><a href="#">Link 1</a></li>
                <li><a href="#">Link 2</a></li>
                <li><a href="#">Link 3</a></li>
                <li><a href="#">Link 4</a></li>
              </ul>
            </div>

          </div>
        </div>
      </footer>

      <!-- End Footer -->

    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/offers/_form.html.erb
<%= simple_form_for(@offer, html: { class: "custom" }) do |f| %>
<fieldset>
  <legend><%=offer_type(@offer) %> Offer</legend>
  <div class="row">
    <div class="large-12 columns">
        <%= f.error_notification %>
    </div>
  </div>
  <div class="row">
    <div class="large-12 columns">
      <%= f.association :plane, input_html: { class: 'medium' }%>
    </div>
  </div>
  <div class="row">
    <div class="large-12 columns">
      <%= f.association :part , input_html: { class: 'medium' }%>
    </div>
  </div>
  <div class="row">
    <div class="large-12 columns">
      <%= f.input :comment %>
    </div>
  </div>
  <div class="row">
    <div class="large-12 columns">
      <%= link_to 'Back', offers_path, :class => "button radius"%>
      <%= f.submit "Save", :class => "button radius" %>
    </div>
  </div>
</fieldset>
<% end %>

app/views/offers/_offer.html.erb
<div class="large-4 small-6 columns">
  <div class="panel">
    <img src="http://placehold.it/240x66&text=Plane Picture">
    <h5><%= offer.plane.name %> <%= offer.part.name if offer.part %></h5>
    <h6 class="subheader">Offered by <%= offer.user.gamecenter_id %></h6>
    <p><%= offer.comment %></p>
    <%if editable?(offer) %>
      <%= link_to 'Edit', edit_offer_path(offer) %>
      <%= link_to 'Delete', offer, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
    <%else%>
      <%= link_to 'Show', offer %>
    <%end%>
  </div>
</div>

app/views/offers/edit.html.erb
<%= render 'form' %>

app/views/offers/index.html.erb
<%= render @offers %>
<%= will_paginate @offers %>

app/views/offers/new.html.erb
<%= render 'form' %>

app/views/offers/show.html.erb
<p>
  <b>Plane:</b>
  <%= @offer.plane.name %>
</p>
<%if @offer.part %>
<p>
  <b>Part:</b>
  <%= @offer.part.name %>
</p>
<%end %>
<p>
  <b>Created by:</b>
  <%= @offer.user.gamecenter_id %>
</p>
<p>
  <b>Created on:</b>
  <%= @offer.created_at %>
</p>
<p>
  <b>Comment:</b>
  <%= @offer.comment %>
</p>

<% if editable?(@offer) %>
<%= link_to 'Edit', edit_offer_path(@offer), class: "button radius"%>
<% end %>
<%= link_to 'Back', offers_path, class: "button radius"%>

app/views/users/edit.html.erb
<%= simple_form_for(@user, :url => :update_user) do |f| %>
<fieldset>
  <legend>Edit Profile</legend>
  <div class="row">
    <div class="large-12 columns">
        <%= f.error_notification %>
    </div>
  </div>
  <div class="row">
    <div class="large-12 columns">
      <%= f.input :gamecenter_id%>
    </div>
  </div>
  <div class="row">
    <div class="large-12 columns">
      <%= f.submit "Save", :class => "button radius" %>
    </div>
  </div>
<% end %>